######################## default configuration ####################
baseURL = "https://qatent.com"
title = "qatent for your patents"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
plugins_js = ["custom"]



############################## navigation ###############################


[[menu.main]]
name = "Team"
URL = "team"
weight = 3

[[menu.main]]
name = "Pricing"
URL = "pricing"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

[[menu.main]]
name = "products"
URL = "products"
weight = 1

[[menu.main]]
name = "Beta"
URL = "https://docs.google.com/forms/d/e/1FAIpQLScsPtTFIdC7zgj4x24y2woYpdIj_CSRIDArNVn3u7wBHZZwTg/viewform"
weight = 6



[[menu.main]]
name = "Roadmap"
URL = "roadmap"
weight = 4

# footer menu left
# [[menu.footer_left]]
# name = "About Us"
# URL = "about"

[[menu.footer_middle]]
name = "Products"
URL = "products"

# footer menu middle
[[menu.footer_middle]]
name = "Pricing"
URL = "pricing"

[[menu.footer_middle]]
name = "Roadmap"
URL = "roadmap"



# footer menu right
# [[menu.footer_right]]
# name = "Privacy Policy"
# URL = "privacy-policy"

[[menu.footer_right]]
name = "About Us"
URL = "about"

[[menu.footer_right]]
name = "Team"
URL = "team"


# [[menu.footer_right]]
# name = "Terms & Conditions"
# URL = "terms-conditions"

# [[menu.footer_right]]
# name = "products"
# URL = "products"

#################### default parameters ################################
[params]
logo = "images/qatent-logo-check.svg"
logo_width = "200px"
# Meta data
description = "qatent brings AI to patents"
author = "qatent"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
# footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Company"
footer_content = "A.I. for patents."
# copyright
copyright = "Design by [Themefisher](https://themefisher.com/) developed by [Gethugothemes](https://gethugothemes.com/), Images by [Undraw](https://undraw.co/) and [Unsplash](https://unsplash.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"

  
############################# social site ########################


[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/QatentPatent"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/qatent/"